# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6c61510f15c0b112b8fc4293ce483ed8ef10f4ea19c252a07b82b20f85a5fdbcaa1c80fe504125b39de766dbe9953d2f123d775b89bb21757d2e28e02e125edd

test:
  secret_key_base: ea1975795435051f430fba23dcd302e8649a1807ffcfbfa2d856cd3aa79740d98597bdf8f956fd31c81eec8c0de6139cde76eebe057f4d2e31bdbb4410ea903c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
